module Website.Landing.Example (output, source) where

-- | The example shown in the hero and the features section.
source :: String
source =
  """module Main where

import Prelude

import Effect (Effect)
import Effect.Console (log)

main :: Effect Unit
main = do
  log "Hello World"
  log "Hello Iris"
"""

-- Generated by Iris 0.1.1 from the source above, then formatted once with Prettier 3.9.9.
output :: String
output =
  """import * as Effect_Console from "../Effect.Console/index.js";
export const main = /* @__PURE__ */ (() => {
  const $action = Effect_Console.log("Hello World");
  return () => {
    const $unit = $action();
    return Effect_Console.log("Hello Iris")();
  };
})();
"""
