module Website.Landing.Example (output, source) where

-- | The example shown in the hero and the features section.
source :: String
source =
  """module Main where

import Prelude

import Effect (Effect)
import Effect.Console (log)

main :: Effect Unit
main = do
  log "Hello from the server,"
  log "the browser,"
  log "and everywhere in between."
"""

-- Generated by Iris 0.1.1 from the source above, then formatted once with Prettier 3.9.9.
output :: String
output =
  """import * as Effect_Console from "../Effect.Console/index.js";
export const main = /* @__PURE__ */ (() => {
  const $action = Effect_Console.log("Hello from the server,");
  return () => {
    const $unit = $action();
    const $action$1 = Effect_Console.log("the browser,");
    const $unit$1 = $action$1();
    return Effect_Console.log("and everywhere in between.")();
  };
})();
"""
