module Website.Landing.Features (features) where

import Prelude

import Data.Maybe (Maybe(..))
import Iris.StyleX as StyleX
import React.Basic (JSX)
import Website.Components.CodeBlock as CodeBlock
import Website.Components.ContentShell as ContentShell
import Website.Landing.Example as Example
import Website.Landing.Section as Section
import Yoga.React.DOM as DOM

type Feature = { title :: String, body :: String }

featureList :: Array Feature
featureList =
  [ { title: "Your Spago workspace"
    , body:
        "Iris discovers sources from spago.yaml and package manifests, so there is no separate project format to maintain."
    }
  , { title: "Incremental queries"
    , body:
        "Results are cached and dependency-tracked. An edit recomputes only the queries it affects, in the build and the editor."
    }
  , { title: "Stable identities"
    , body:
        "Queries refer to stable identities instead of source ranges, so reformatting a file causes minimal recomputation."
    }
  , { title: "Optimised output"
    , body:
        "Effect blocks compile to flat thunks, integer arithmetic to JavaScript operators, and tail calls to loops."
    }
  ]

styles = StyleX.create
  { section: { paddingBlock: 64, scrollMarginTop: "var(--nav-height)" }
  , layout:
      { alignItems: "start"
      , display: "grid"
      , gap: 56
      , gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 460px), 1fr))"
      }
  , copy: { minWidth: 0 }
  , introduction:
      { display: "flex"
      , flexDirection: "column"
      , gap: 14
      , marginBlockEnd: 40
      , maxWidth: 640
      }
  , list:
      { display: "grid"
      , gap: "28px 32px"
      , gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 220px), 1fr))"
      , listStyle: "none"
      , padding: 0
      }
  , item:
      { borderBlockStartColor: "var(--border-default)"
      , borderBlockStartStyle: "solid"
      , borderBlockStartWidth: 1
      , display: "flex"
      , flexDirection: "column"
      , gap: 8
      , paddingBlockStart: 16
      }
  , itemTitle:
      { fontSize: 17
      , fontWeight: 500
      , letterSpacing: "-0.015em"
      , lineHeight: 1.25
      }
  , itemBody:
      { color: "var(--text-secondary)"
      , fontSize: 15
      , lineHeight: 1.65
      , textWrap: "pretty"
      }
  , code:
      { display: "flex"
      , flexDirection: "column"
      , gap: 12
      , insetBlockStart: "calc(var(--nav-height) + 24px)"
      , minWidth: 0
      , position: "sticky"
      }
  }

styleProps = StyleX.recordProps styles

features :: JSX
features =
  DOM.section
    { className: styleProps.section.className
    , id: "features"
    , "aria-labelledby": "features-heading"
    }
    [ DOM.div ContentShell.contentShell
        [ DOM.div styleProps.layout
            [ DOM.div styleProps.copy
                [ DOM.div styleProps.introduction
                    [ Section.heading
                        { id: "features-heading"
                        , text: "PureScript, "
                        , emphasis: "compiled incrementally."
                        }
                    , Section.lead
                        "Instead of a fixed sequence of compiler phases, Iris models compilation as incrementally computed queries. The compiler and language server share them, so both stay fast as you edit."
                    ]
                , DOM.ul styleProps.list (map feature featureList)
                ]
            , DOM.div styleProps.code
                [ CodeBlock.codeBlock
                    { code: Example.source
                    , filename: "src/Main.purs"
                    , highlight: []
                    , language: CodeBlock.PureScript
                    , lineNumbers: true
                    , note: Nothing
                    , surface: CodeBlock.Flat
                    }
                , CodeBlock.codeBlock
                    { code: Example.output
                    , filename: "output/Main/index.js"
                    , highlight: []
                    , language: CodeBlock.JavaScript
                    , lineNumbers: false
                    , note: Just "Generated by Iris 0.1.1 and formatted with Prettier."
                    , surface: CodeBlock.Flat
                    }
                ]
            ]
        ]
    ]
  where
  feature { title, body } =
    DOM.li styleProps.item
      [ DOM.h3 styleProps.itemTitle title
      , DOM.p styleProps.itemBody body
      ]
